/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffClaimsRouteImport } from './routes/staff.claims'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims.$claimId'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffClaimsRoute = StaffClaimsRouteImport.update({
  id: '/staff/claims',
  path: '/staff/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/staff/claims': typeof StaffClaimsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/staff/claims': typeof StaffClaimsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/staff/claims': typeof StaffClaimsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/submit' | '/claims/$claimId' | '/staff/claims'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/submit' | '/claims/$claimId' | '/staff/claims'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/submit'
    | '/claims/$claimId'
    | '/staff/claims'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SubmitRoute: typeof SubmitRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  StaffClaimsRoute: typeof StaffClaimsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/claims': {
      id: '/staff/claims'
      path: '/staff/claims'
      fullPath: '/staff/claims'
      preLoaderRoute: typeof StaffClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SubmitRoute: SubmitRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  StaffClaimsRoute: StaffClaimsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
